//
//  ScripturesInterfaces.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

// MARK: - Entity
struct ScriptureEntity: Codable {
    let title: String
    let name: String
    let description: String
    let resourceTag: ResourceTag
    var tags: [String] {
        return []
    }

    var shortDisplayTitle: String {
        if title.contains("Dhammapada") || title.contains("Sayings of the Dhamma") {
            return "Dhammapada"
        }
        if title.contains("Majjhimanik") {
            return "Majjhima Nikaya"
        }
        if title.contains("Saṁyutta") || title.contains("Linked Discourses") {
            return "Samyutta Nikaya"
        }
        if title.contains("Aṅguttara") || title.contains("Numbered Discourses") {
            return "Anguttara Nikaya"
        }
        if title.contains("Sutta Nip") || title.contains("Anthology of Discourses") {
            return "Sutta Nipata"
        }
        if title.contains("Basic Passages") {
            return "Basic Passages"
        }
        if title.contains("Compendium of States of Phenomena") {
            return "Compendium of States"
        }
        if title.contains("Book of Analysis") {
            return "Book of Analysis"
        }
        return title
    }
}

struct ScriptureCollectionEntity: Equatable {
    let title: String
    let subtitle: String
    let resourceTag: ResourceTag
}

// MARK: - Viewable
protocol ScriptureViewable: AnyObject {
    var presenter: ScripturePresentable? { get set }
    func displayBrowseContent(scriptures: [ScriptureEntity], collections: [ScriptureCollectionEntity])
    func displaySearchResults(_ scriptures: [ScriptureEntity])
}

// MARK: - Interactable
protocol ScriptureInteractable: AnyObject {
    var presenter: ScripturePresentable? { get set }
    func fetchScriptures()
    func search(keyword: String)
    func filter(by category: String)
}

// MARK: - Presentable
protocol ScripturePresentable: AnyObject {
    var view: ScriptureViewable? { get set }
    var interactor: ScriptureInteractable? { get set }
    var router: ScriptureRoutable? { get set }

    func viewDidLoad()
    func didSelectScripture(_ scripture: ScriptureEntity)
    func search(keyword: String)
    func filter(by category: String)
}

// MARK: - Routable
protocol ScriptureRoutable: AnyObject {
    func routeToScriptureDetail(from view: ScriptureViewable, scripture: ScriptureEntity)
}
