//
//  ScripturesInteractor.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift


// MARK: - Interactor
final class ScriptureInteractor: ScriptureInteractable {
    weak var presenter: ScripturePresentable?
    private var allScriptures: [ScriptureEntity] = []

    func fetchScriptures() {

        guard let scriptureURL = Bundle.main.url(forResource: "Scriptures.json", withExtension: nil) else { return }
        
        guard let data = try? Data(contentsOf: scriptureURL) else { return }
        
        do {
            allScriptures = try JSONDecoder().decode([ScriptureEntity].self, from: data)
        } catch {}

        presenter?.view?.displayBrowseContent(
            scriptures: allScriptures,
            collections: buildCollections(from: allScriptures)
        )
    }

    func search(keyword: String) {
        var filtered: [ScriptureEntity] = []
        if keyword.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            filtered = allScriptures
        } else {
            filtered = allScriptures.filter {
                $0.title.lowercased().contains(keyword.lowercased()) ||
                $0.description.lowercased().contains(keyword.lowercased())
            }
        }

        presenter?.view?.displaySearchResults(filtered)
    }

    func filter(by category: String) {
        if category == "All" {
            presenter?.view?.displaySearchResults(allScriptures)
            return
        }
        let filtered = allScriptures.filter { $0.tags.contains(category) }
        presenter?.view?.displaySearchResults(filtered)
    }

    private func buildCollections(from scriptures: [ScriptureEntity]) -> [ScriptureCollectionEntity] {
        let order: [ResourceTag] = [
            .minorCollection,
            .middleDiscourses,
            .linkedDiscourses,
            .numberedDiscourses,
            .longDiscourses
        ]

        let grouped = Dictionary(grouping: scriptures, by: \.resourceTag)
        return order.compactMap { tag in
            guard grouped[tag]?.isEmpty == false else { return nil }
            return ScriptureCollectionEntity(
                title: title(for: tag),
                subtitle: subtitle(for: tag),
                resourceTag: tag
            )
        }
    }

    private func title(for tag: ResourceTag) -> String {
        switch tag {
        case .minorCollection:
            return "Dhammapada"
        case .middleDiscourses:
            return "Majjhima Nikaya"
        case .linkedDiscourses:
            return "Samyutta Nikaya"
        case .numberedDiscourses:
            return "Anguttara Nikaya"
        case .longDiscourses:
            return "Sutta Nipata"
        case .vinayaPitaka:
            return "Vinaya Pitaka"
        case .abhidhammaPitaka:
            return "Abhidhamma Pitaka"
        }
    }

    private func subtitle(for tag: ResourceTag) -> String {
        switch tag {
        case .minorCollection:
            return "Verses on the path of wisdom"
        case .middleDiscourses:
            return "Middle Length Discourses"
        case .linkedDiscourses:
            return "Connected Discourses"
        case .numberedDiscourses:
            return "Numerical Discourses"
        case .longDiscourses:
            return "Ancient inspired verses"
        case .vinayaPitaka:
            return "Monastic discipline"
        case .abhidhammaPitaka:
            return "Analytical teachings"
        }
    }
}
