//
//  ScripturesWireframe.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

// MARK: - Router
final class ScriptureRouter: ScriptureRoutable {
    weak var view: UIViewController?
    
    static func createModule() -> UIViewController {
        let view = ScriptureViewController()
        let presenter = ScripturePresenter()
        let interactor = ScriptureInteractor()
        let router = ScriptureRouter()

        view.presenter = presenter
        presenter.view = view
        presenter.interactor = interactor
        presenter.router = router
        interactor.presenter = presenter

        router.view = view
        
        return view
    }
    
    func routeToScriptureDetail(from view: ScriptureViewable, scripture: ScriptureEntity) {
        guard let vc = view as? UIViewController else { return }
        let detailVC = ScriptureReaderVC(scripture: scripture) 
        detailVC.title = scripture.title
        detailVC.modalPresentationStyle = .fullScreen
//        vc.navigationController?.pushViewController(detailVC, animated: true)
        vc.present(detailVC, animated: true)
    }
}
