//
//  ScripturesInterfaces.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

// MARK: - Entity
struct ScriptureEntity: Codable {
    let title: String
    let name: String
    let description: String
    let resourceTag: ResourceTag
    var tags: [String] {
        return []
    }
}

// MARK: - Viewable
protocol ScriptureViewable: AnyObject {
    var presenter: ScripturePresentable? { get set }
    func displayScriptures(_ scriptures: [ScriptureEntity])
}

// MARK: - Interactable
protocol ScriptureInteractable: AnyObject {
    var presenter: ScripturePresentable? { get set }
    func fetchScriptures()
    func search(keyword: String)
    func filter(by category: String)
}

// MARK: - Presentable
protocol ScripturePresentable: AnyObject {
    var view: ScriptureViewable? { get set }
    var interactor: ScriptureInteractable? { get set }
    var router: ScriptureRoutable? { get set }

    func viewDidLoad()
    func didSelectScripture(_ scripture: ScriptureEntity)
    func search(keyword: String)
    func filter(by category: String)
}

// MARK: - Routable
protocol ScriptureRoutable: AnyObject {
    func routeToScriptureDetail(from view: ScriptureViewable, scripture: ScriptureEntity)
}
