//
//  ScripturesPresenter.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

// MARK: - Presenter
final class ScripturePresenter: ScripturePresentable {
    weak var view: ScriptureViewable?
    var interactor: ScriptureInteractable?
    var router: ScriptureRoutable?

    func viewDidLoad() {
        interactor?.fetchScriptures()
    }

    func didSelectScripture(_ scripture: ScriptureEntity) {
        guard let view = view else { return }
        router?.routeToScriptureDetail(from: view, scripture: scripture)
    }

    func search(keyword: String) {
        interactor?.search(keyword: keyword)
    }

    func filter(by category: String) {
        interactor?.filter(by: category)
    }
}
