//
//  ScripturesInteractor.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift


// MARK: - Interactor
final class ScriptureInteractor: ScriptureInteractable {
    weak var presenter: ScripturePresentable?
    private var allScriptures: [ScriptureEntity] = []

    func fetchScriptures() {

        guard let scriptureURL = Bundle.main.url(forResource: "Scriptures.json", withExtension: nil) else { return }
        
        guard let data = try? Data(contentsOf: scriptureURL) else { return }
        
        do {
            allScriptures = try JSONDecoder().decode([ScriptureEntity].self, from: data)
        } catch {}
        
        presenter?.view?.displayScriptures(allScriptures)
    }

    func search(keyword: String) {
        var filtered: [ScriptureEntity] = []
        if keyword.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            filtered = allScriptures
        } else {
            filtered = allScriptures.filter {
                $0.title.lowercased().contains(keyword.lowercased()) ||
                $0.description.lowercased().contains(keyword.lowercased())
            }
        }
       
        presenter?.view?.displayScriptures(filtered)
    }

    func filter(by category: String) {
        if category == "All" {
            presenter?.view?.displayScriptures(allScriptures)
            return
        }
        let filtered = allScriptures.filter { $0.tags.contains(category) }
        presenter?.view?.displayScriptures(filtered)
    }
}
