//
//  MeditationInterfaces.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum Mood: CaseIterable, Equatable {
    case veryHappy, happy, neutral, sad, verySad

    var icon: UIImage? {
        switch self {
        case .veryHappy: Asset.Assets.icMoodHoanhi.image
        case .happy:  Asset.Assets.icMoodAnnhien.image
        case .neutral:  Asset.Assets.icMoodBinhthan.image
        case .sad:  Asset.Assets.icMoodPhienmuon.image
        case .verySad:  Asset.Assets.icMoodKhodau.image
        }
    }
    
    var text: String {
        switch self {
        case .veryHappy: "Joy"
        case .happy: "Serenity"
        case .neutral: "Calmness"
        case .sad: "Worry"
        case .verySad: "Suffering"
        }
    }
}

protocol MeditationMoodViewable: AnyObject {
    var presenter: MeditationMoodPresentable? { get set }
    func showUserInfo(name: String)
    func updateSelectedMood(_ mood: Mood)
    func reloadTableView()
}
