//
//  MeditationInteractor.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

protocol MeditationMoodInteractable: AnyObject {
    var presenter: MeditationMoodInteractorOutput? { get set }
    func fetchUserInfo()
}

protocol MeditationMoodInteractorOutput: AnyObject {
    func didFetchUserInfo(name: String)
}

final class MeditationMoodInteractor: MeditationMoodInteractable {
    weak var presenter: MeditationMoodInteractorOutput?

    func fetchUserInfo() {
        let name = "Thiền Sinh A"
        presenter?.didFetchUserInfo(name: name)
    }
}
