//
//  MeditationWireframe.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol MeditationMoodRoutable: AnyObject {
    func navigateToMeditation()
}

final class MeditationMoodRouter: MeditationMoodRoutable {
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
            let view = MeditationMoodViewController()
            let presenter = MeditationMoodPresenter()
            let interactor = MeditationMoodInteractor()
            let router = MeditationMoodRouter()

            view.presenter = presenter

            presenter.view = view
            presenter.interactor = interactor
            presenter.router = router

            interactor.presenter = presenter
            router.viewController = view

            return view
        }
    
    func navigateToMeditation() {
        // push MeditationScreen
        
        let vc = MeditationTimerRouter.createModule()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
