//
//  HistoryInteractor.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class HistoryInteractor {
}

// MARK: - Extensions -

extension HistoryInteractor: HistoryInteractorInterface {
}
