//
//  HistoryWireframe.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class HistoryWireframe: BaseWireframe<HistoryViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = HistoryViewController()
        super.init(viewController: moduleViewController)

        let interactor = HistoryInteractor()
        let presenter = HistoryPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension HistoryWireframe: HistoryWireframeInterface {
}
