//
//  HistoryViewController.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class HistoryViewController: UIViewController {
    
    // MARK: - Public properties -
    
    var presenter: HistoryPresenterInterface!
    
    // MARK: - Private properties -
    
    private let disposeBag = DisposeBag()
    private let tableView = UITableView()
    private var conversations: [ConversationCodable] = []
    private let summaryCardView = UIView()
    private let summaryLabel = UILabel()
    private lazy var backgroundImageView: UIImageView = {
        let imageView = UIImageView(image: Asset.Assets.buddaConversation.image)
        imageView.contentMode = .scaleAspectFill
        imageView.alpha = 0.14
        return imageView
    }()
    private let backgroundOverlayView = UIView()
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.setNavigationBarHidden(true, animated: false)
        setupView()
        setupTableView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        loadConversations()
    }
    
    private func setupTableView() {
        let titleLabel = UILabel()
        titleLabel.text = "History"
        titleLabel.font = FontFamily.PlayfairDisplay.bold.font(size: 28)
        titleLabel.textAlignment = .center
        titleLabel.textColor = UIColor(hexString: "#4B3621")

        backgroundOverlayView.backgroundColor = UIColor.white.withAlphaComponent(0.24)

        view.addSubview(backgroundImageView)
        view.addSubview(backgroundOverlayView)
        view.addSubview(tableView)
        view.addSubview(titleLabel)
        view.addSubview(summaryCardView)
        summaryCardView.addSubview(summaryLabel)

        summaryCardView.backgroundColor = UIColor.white.withAlphaComponent(0.58)
        summaryCardView.layer.cornerRadius = 22
        summaryCardView.layer.borderWidth = 1
        summaryCardView.layer.borderColor = UIColor.white.withAlphaComponent(0.45).cgColor

        summaryLabel.font = FontFamily.Inter28pt.medium.font(size: 14)
        summaryLabel.textColor = UIColor(hexString: "#6E6257")
        summaryLabel.numberOfLines = 0
        summaryLabel.text = "Return to a past conversation or begin a fresh question from the empty state."

        titleLabel.snp.makeConstraints {
            $0.top.equalTo(view.safeAreaLayoutGuide.snp.top).offset(10)
            $0.centerX.equalToSuperview()
        }

        summaryCardView.snp.makeConstraints { make in
            make.top.equalTo(titleLabel.snp.bottom).offset(16)
            make.left.right.equalToSuperview().inset(16)
        }

        summaryLabel.snp.makeConstraints { make in
            make.edges.equalToSuperview().inset(16)
        }
        
        backgroundImageView.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }
        
        backgroundOverlayView.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }
        tableView.snp.makeConstraints { make in
            make.left.right.bottom.equalToSuperview()
            make.top.equalTo(summaryCardView.snp.bottom).offset(12)
        }

        tableView.backgroundColor = .clear
        tableView.contentInset = UIEdgeInsets(top: 4, left: 0, bottom: 20, right: 0)
        tableView.dataSource = self
        tableView.delegate = self
        tableView.separatorStyle = .none
        tableView.register(ConversationCell.self, forCellReuseIdentifier: ConversationCell.reuseId)
        tableView.register(ConversationEmptyTVC.self, forCellReuseIdentifier: "ConversationEmptyTVC")
    }
    
    private func loadConversations() {
        let dataManager = ChatDataManager()
        conversations = dataManager.fetchAllConversations().filter({!$0.messages.isEmpty})
        tableView.reloadData()
    }
    
    func presentChatVC(conversation: ConversationCodable? = nil) {
        let vc = ChatRouter.createModule(conversation: conversation )
        vc.modalPresentationStyle = .fullScreen
        present(vc, animated: true)
    }
    
    func presentEmptyChatVC() {
        let vc = WisdomQuestionLauncherViewController()
        vc.delegate = self
        vc.modalPresentationStyle = .fullScreen
        present(vc, animated: true)
    }
}

extension HistoryViewController: WisdomQuestionLauncherDelegate {
    func wisdomQuestionLauncher(_ launcher: WisdomQuestionLauncherViewController, didCreate conversation: ConversationCodable) {
        launcher.dismiss(animated: true) { [weak self] in
            self?.presentChatVC(conversation: conversation)
        }
    }
}

extension HistoryViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if indexPath.section == 0 {
            return 400
        } else if indexPath.section == 1 {
            return 140
        } else {
            return 0
        }
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if section == 0 {
            return conversations.count == 0 ? 1 : 0
        }
        
        return conversations.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.section == 0 {
            guard let cell = tableView.dequeueReusableCell(withIdentifier: "ConversationEmptyTVC", for: indexPath) as? ConversationEmptyTVC else {
                return UITableViewCell()
            }
            
            cell.tappedStartHandler = {[weak self] in
                self?.presentEmptyChatVC()
            }
            
            return cell
        } else if indexPath.section == 1 {
            let conversation = conversations[indexPath.row]
            guard let cell = tableView.dequeueReusableCell(withIdentifier: ConversationCell.reuseId, for: indexPath) as? ConversationCell else {
                return UITableViewCell()
            }
            
            cell.configure(with: conversation, index: indexPath.row)
            return cell
        } else {
            return UITableViewCell()
        }
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        // Navigate to chat screen
        guard indexPath.section == 1 else { return }
        tableView.deselectRow(at: indexPath, animated: true)
        
        let conversation = conversations[indexPath.row]
        presentChatVC(conversation: conversation)
    }
    
    
    // MARK: - Swipe to Delete
//    func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
//        // Chỉ cho phép swipe ở section 1
//        guard indexPath.section == 1 else { return nil }
//        
//        // Tạo hành động Delete
//        let deleteAction = UIContextualAction(style: .destructive, title: "Delete") { [weak self] (_, _, completionHandler) in
//            guard let self = self else { return }
//            
//            // Xoá phần tử trong mảng dữ liệu
//            self.conversations.remove(at: indexPath.row)
//            
//            // Cập nhật lại TableView
//            if self.conversations.isEmpty {
//                tableView.reloadData()
//            } else {
//                tableView.deleteRows(at: [indexPath], with: .automatic)
//            }
//            
//            // Gọi callback để hoàn thành hành động
//            completionHandler(true)
//        }
//        
//        deleteAction.backgroundColor = .systemRed
//        
//        // Cấu hình swipe
//        let configuration = UISwipeActionsConfiguration(actions: [deleteAction])
//        configuration.performsFirstActionWithFullSwipe = true
//        
//        return configuration
//    }
}

// MARK: - Extensions -

extension HistoryViewController: HistoryViewInterface {
}

private extension HistoryViewController {
    
    func setupView() {
        view.backgroundColor = .colorFDF6ED
        let output = History.ViewOutput()
        
        let input = presenter.configure(with: output)
    }
    
}
