//
//  HistoryPresenter.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class HistoryPresenter {
    
    // MARK: - Private properties -

    private unowned let view: HistoryViewInterface
    private let interactor: HistoryInteractorInterface
    private let wireframe: HistoryWireframeInterface

    // MARK: - Lifecycle -

    init(view: HistoryViewInterface, interactor: HistoryInteractorInterface, wireframe: HistoryWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension HistoryPresenter: HistoryPresenterInterface {

    func configure(with output: History.ViewOutput) -> History.ViewInput {
        return History.ViewInput()
    }

}
