//
//  HistoryInterfaces.swift
//  TalkToBudda
//
//  Created by mac on 6/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol HistoryWireframeInterface: WireframeInterface {
}

protocol HistoryViewInterface: ViewInterface {
}

protocol HistoryPresenterInterface: PresenterInterface {
    func configure(with output: History.ViewOutput) -> History.ViewInput
}

protocol HistoryInteractorInterface: InteractorInterface {
}

enum History {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}
