//
//  ChatWireframe.swift
//  TalkToBudda
//
//  Created by mac on 5/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

class ChatRouter: ChatRoutable {
    weak var view: UIViewController?
    
    static func createModule(conversation: ConversationCodable? = nil) -> UIViewController {
        let view = ChatViewController()
        let presenter = ChatPresenter()
        let interactor = ChatInteractor(conversation: conversation)
        let router = ChatRouter()

        view.presenter = presenter
        presenter.view = view
        presenter.interactor = interactor
        interactor.presenter = presenter
        interactor.view = view
        router.view = view
        
        return view
    }
}
