//
//  ChatInteractor.swift
//  TalkToBudda
//
//  Created by mac on 5/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

class ChatInteractor: ChatInteractable {
    weak var presenter: ChatPresenter?
    weak var view: ChatViewable?

    let networkService = NetworkService()
   

    private var messages: [ChatMessage] = []
    private let oldConversation: ConversationCodable?
    private var conversation: ConversationCodable
    private var selectedCharacter: CharacterType?
    required init(conversation: ConversationCodable? = nil) {
        self.oldConversation = conversation
        self.conversation = conversation ?? ChatDataManager.shared.createConversation(title: "", character: nil)
        self.selectedCharacter = conversation?.selectedCharacter
    }
    
    func fetchInitialMessages() {
        view?.updateCharacterSelection(conversation.selectedCharacter)

        if let _conversation = oldConversation {
            _conversation.messages.forEach { chat in
                messages.append(chat)
            }
            view?.showNav()
        } else {
            guard let url = Bundle.main.url(forResource: "TalkToBuddha_Questions", withExtension: "json"), let data = try? Data(contentsOf: url) else { return }
            
            if let samleQuestions = try? JSONDecoder().decode([[String: String]].self, from: data) {
                
                while messages.count < 2 {
                    let dict = samleQuestions.randomElement() ?? [:]
                    
                    if let question = dict["question"], !question.isEmpty, let answer = dict["answer"], !answer.isEmpty {
                        let chat1 = ChatMessage(text: question, sender: .user)
                        let chat2 = ChatMessage(text: answer, sender: .bot)
                        messages.append(chat1)
                        messages.append(chat2)
                    }

                }
            }
        }
      
        if messages.isEmpty {
            let chat = ChatMessage(text: makeGreetingMessage(), sender: .bot)
            messages.append(chat)
        }
    
        view?.displayMessages(messages)
    }

    func sendMessage(_ text: String) {

        let userMessage = ChatMessage(text: text, sender: .user)
        messages.append(userMessage)
        view?.appendMessage(userMessage)

        if !PreferenceService.shared.hasStartedFirstCharacterChat {
            PreferenceService.shared.hasStartedFirstCharacterChat = true
        }
        
        
        let character = selectedCharacter ?? .buddha
        networkService.sendQuestion(text, conversation: conversation, characterType: character) {[weak self] result in
            guard let self else { return }
            switch result {
            case .success(let buddhistResponse):                
                let botMessage = ChatMessage(text: buddhistResponse.answer, sender: .bot)
                ChatDataManager.shared.addMessage(chat: userMessage, to: self.conversation)
                ChatDataManager.shared.addMessage(chat: botMessage, to: self.conversation)
                ConditionServices.shared.increasetChat()

                self.messages.append(botMessage)
                DispatchQueue.main.async {
                    self.view?.appendMessage(botMessage)
                }

            case .failure(let error):
                print("Lỗi xảy ra: \(error.localizedDescription)")
                let botMessage = ChatMessage(text: "Sorry, Something went wrong.\nPlease try again later.", sender: .bot)
                self.messages.append(botMessage)
                DispatchQueue.main.async {
                    self.view?.appendMessage(botMessage)
                }
            }
        }
    }
    
    func updateSelectedCharacter(_ character: CharacterType) {
        selectedCharacter = character
        ChatDataManager.shared.updateConversationCharacter(conversationId: conversation.id, character: character)
        ChatDataManager.shared.updateWisdomContext(conversationId: conversation.id, wisdomContext: nil)
        
        // Update the conversation object
        conversation.selectedCharacter = character
        conversation.selectedWisdomSituationId = nil
        conversation.selectedWisdomSituationTitle = nil
        conversation.selectedWisdomMatchReason = nil
        
        // Keep exactly one opening bot greeting for a fresh conversation.
        if shouldReplaceOpeningGreeting {
            messages[0] = ChatMessage(text: character.greetingMessage, sender: .bot)
            view?.displayMessages(messages)
            return
        }

        // Show character-specific greeting if this is a new conversation
        if messages.isEmpty {
            let greetingMessage = ChatMessage(text: character.greetingMessage, sender: .bot)
            messages.append(greetingMessage)
            ChatDataManager.shared.addMessage(chat: greetingMessage, to: conversation)
            view?.appendMessage(greetingMessage)
        }
    }

    func restartConversation(with character: CharacterType) {
        selectedCharacter = character
        conversation = ChatDataManager.shared.createConversation(title: "", character: character)
        messages.removeAll()

        let greetingMessage = ChatMessage(text: character.greetingMessage, sender: .bot)
        messages.append(greetingMessage)
        ChatDataManager.shared.addMessage(chat: greetingMessage, to: conversation)

        view?.updateCharacterSelection(character)
        view?.displayMessages(messages)
    }

    private func makeGreetingMessage() -> String {
        if let situation = conversation.selectedWisdomSituationTitle,
           let character = conversation.selectedCharacter {
            return "\(character.greetingMessage)\n\nYou chose to reflect on: \(situation)"
        }

        if let character = selectedCharacter {
            return character.greetingMessage
        }

        return "Welcome, dear seeker of peace. May your heart find clarity and your mind discover stillness as we journey together through the path of understanding."
    }

    private var shouldReplaceOpeningGreeting: Bool {
        guard oldConversation == nil, messages.count == 1 else { return false }
        return messages.first?.sender == .bot
    }
}
