//
//  ChatInterfaces.swift
//  TalkToBudda
//
//  Created by mac on 5/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ChatViewable: AnyObject {
    func showNav()
    func displayMessages(_ messages: [ChatMessage])
    func appendMessage(_ message: ChatMessage)
    func toogleLoading(_ loading: Bool)
    func updateCharacterSelection(_ character: CharacterType?)
}

protocol ChatInteractable: AnyObject {
    init(conversation: ConversationCodable?)
    func fetchInitialMessages()
    func sendMessage(_ text: String)
    func updateSelectedCharacter(_ character: CharacterType)
}

protocol ChatPresentable: AnyObject {
    func viewDidLoad()
    func userDidSendMessage(_ text: String)
    func userReceivedAnswer(chat: ChatMessage)
    func updateSelectedCharacter(_ character: CharacterType)
}

protocol ChatRoutable: AnyObject {
    static func createModule(conversation: ConversationCodable?) -> UIViewController
}
