//
//  ChatPresenter.swift
//  TalkToBudda
//
//  Created by mac on 5/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

class ChatPresenter: ChatPresentable {
    weak var view: ChatViewable?
    var interactor: ChatInteractable?

    private var conversation: ConversationCodable?
    private var selectedCharacter: CharacterType?
    
    func viewDidLoad() {        
        interactor?.fetchInitialMessages()
    }

    func userDidSendMessage(_ text: String) {
        interactor?.sendMessage(text)
    }
    
    func userReceivedAnswer(chat: ChatMessage) {
        
    }
    
    func updateSelectedCharacter(_ character: CharacterType) {
        selectedCharacter = character
        interactor?.updateSelectedCharacter(character)
    }

    func restartConversation(with character: CharacterType) {
        selectedCharacter = character
        interactor?.restartConversation(with: character)
    }
}
