//
//  ChatViewController.swift
//  TalkToBudda
//
//  Created by mac on 5/5/25.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import SnapKit

class ChatViewController: UIViewController, ChatViewable {
    var presenter: ChatPresentable?

    private var messages: [ChatMessage] = []
    private let tableView = UITableView()
    private let inputBar = InputBarView()
    private var selectedCharacter: CharacterType?
    private lazy var selectedGuide = Character(type: .buddha)
    private let dockContainerView = UIView()
    private var tableTopConstraint: Constraint?
    private lazy var navView: UIView = {
        let view = UIView()

        return view
    }()

    private lazy var backButton: UIButton = {
        let button = UIButton()
        button.isHidden = true
        button.setImage(Asset.Assets.icBack.image.withRenderingMode(.alwaysTemplate), for: .normal)
        button.imageView?.contentMode = .scaleAspectFit
        button.tintColor = .color4B3621
        button.backgroundColor = UIColor(hexString: "#F7EFE5")
        button.layer.cornerRadius = 22
        button.addTarget(self, action: #selector(tappedBackButton(_:)), for: .touchUpInside)
        return button
    }()

    private lazy var guideListButton: UIButton = {
        let button = UIButton()
        button.isHidden = true
        let iconConfig = UIImage.SymbolConfiguration(pointSize: 18, weight: .medium)
        button.setImage(UIImage(systemName: "person.2", withConfiguration: iconConfig), for: .normal)
        button.tintColor = .color4B3621
        button.backgroundColor = UIColor(hexString: "#F7EFE5")
        button.layer.cornerRadius = 22
        button.addTarget(self, action: #selector(tappedCharacterButton(_:)), for: .touchUpInside)
        return button
    }()

    private lazy var subtitleLabel: UILabel = {
        let label = UILabel()
        label.text = "Best for calm reflection"
        label.font = FontFamily.Inter28pt.medium.font(size: 13)
        label.textColor = UIColor(hexString: "#7A624B")
        label.textAlignment = .center
        label.numberOfLines = 1
        return label
    }()

    private lazy var titleLabel: UILabel = {
        let label = UILabel()
        label.text = "Buddha"
        label.font = FontFamily.PlayfairDisplay.bold.font(size: 28)
        label.textAlignment = .center
        label.textColor = UIColor(hexString: "#4B3621")
        label.numberOfLines = 1
        return label
    }()

    private var isLoading: Bool = false {
        didSet {
            inputBar.uploadLoadingState(isLoading)
        }
    }

    private lazy var premiumPromptView: UIView = {
        let view = UIView()
        view.backgroundColor = UIColor(hexString: "#FBF5EE")
        view.layer.cornerRadius = 20
        view.layer.borderWidth = 1
        view.layer.borderColor = UIColor(hexString: "#E9D8C5").cgColor
        view.isHidden = true
        return view
    }()

    private lazy var premiumIconView: UIImageView = {
        let imageView = UIImageView(image: UIImage(systemName: "sparkles"))
        imageView.tintColor = UIColor(hexString: "#D8A24F")
        imageView.contentMode = .scaleAspectFit
        return imageView
    }()

    private lazy var chatCountLabel: UILabel = {
        let label = UILabel()
        label.font = FontFamily.Inter28pt.medium.font(size: 15)
        label.textColor = UIColor(hexString: "#6C5034")
        label.textAlignment = .left
        return label
    }()

    private lazy var storeButton: UIButton = {
        let button = UIButton()
        button.setTitle("Get More", for: .normal)
        button.setTitleColor(.white, for: .normal)
        button.titleLabel?.font = FontFamily.Inter28pt.semiBold.font(size: 16)
        button.backgroundColor = UIColor(hexString: "#D3A05D")
        button.layer.cornerRadius = 18
        button.addTarget(self, action: #selector(tappedStoreButton(_:)), for: .touchUpInside)
        return button
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.setNavigationBarHidden(true, animated: false)
        setupUI()
        setupKeyboardObservers()
        updatePremiumPromptVisibility()
        presenter?.viewDidLoad()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        updatePremiumPromptVisibility()
        updateChatCountLabel()
    }

    deinit {
        removeKeyboardObservers()
    }

    private func setupUI() {
        view.backgroundColor = .colorFDF6ED
        view.addSubview(navView)
        view.addSubview(tableView)
        view.addSubview(dockContainerView)

        dockContainerView.addSubview(premiumPromptView)
        dockContainerView.addSubview(inputBar)

        navView.addSubview(backButton)
        navView.addSubview(guideListButton)
        navView.addSubview(subtitleLabel)
        navView.addSubview(titleLabel)

        premiumPromptView.addSubview(premiumIconView)
        premiumPromptView.addSubview(chatCountLabel)
        premiumPromptView.addSubview(storeButton)

        dockContainerView.backgroundColor = UIColor.white.withAlphaComponent(0.68)
        dockContainerView.layer.cornerRadius = 28
        dockContainerView.layer.borderWidth = 1
        dockContainerView.layer.borderColor = UIColor.white.withAlphaComponent(0.78).cgColor

        tableView.register(ChatMessageCell.self, forCellReuseIdentifier: "ChatMessageCell")
        tableView.register(BuddaChatMessageCell.self, forCellReuseIdentifier: "BuddaChatMessageCell")
        tableView.register(ChatLoadingTVC.self, forCellReuseIdentifier: "ChatLoadingTVC")


        tableView.dataSource = self
        tableView.separatorStyle = .none
        tableView.backgroundColor = .clear
        tableView.showsVerticalScrollIndicator = false
        tableView.contentInset = UIEdgeInsets(top: 4, left: 0, bottom: 12, right: 0)
        tableView.rowHeight = UITableView.automaticDimension
        tableView.estimatedRowHeight = 120

        inputBar.onSend = { [weak self] text in
            self?.presenter?.userDidSendMessage(text)
        }

        // Add tap gesture to dismiss keyboard only when tapping on tableView
        let tapGesture = UITapGestureRecognizer(target: self, action: #selector(dismissKeyboard))
        tapGesture.cancelsTouchesInView = false
        tableView.addGestureRecognizer(tapGesture)

        navView.snp.makeConstraints { make in
            make.left.right.equalToSuperview()
            make.height.equalTo(84)
            make.top.equalTo(view.safeAreaLayoutGuide.snp.top)
        }

        tableView.snp.makeConstraints { make in
            make.left.right.equalToSuperview()
            tableTopConstraint = make.top.equalTo(navView.snp.bottom).offset(8).constraint
            make.bottom.equalTo(dockContainerView.snp.top).offset(-10)
        }

        dockContainerView.snp.makeConstraints { make in
            make.left.right.equalToSuperview().inset(20)
            make.bottom.equalTo(view.safeAreaLayoutGuide.snp.bottom).offset(-8)
        }

        premiumPromptView.snp.makeConstraints { make in
            make.top.left.right.equalToSuperview().inset(8)
            make.height.equalTo(54)
        }

        premiumIconView.snp.makeConstraints { make in
            make.left.equalToSuperview().inset(16)
            make.centerY.equalToSuperview()
            make.width.height.equalTo(18)
        }

        chatCountLabel.snp.makeConstraints { make in
            make.left.equalTo(premiumIconView.snp.right).offset(10)
            make.centerY.equalToSuperview()
            make.right.equalTo(storeButton.snp.left).offset(-8)
        }

        storeButton.snp.makeConstraints { make in
            make.right.equalToSuperview().inset(10)
            make.centerY.equalToSuperview()
            make.width.equalTo(106)
            make.height.equalTo(38)
        }

        inputBar.snp.makeConstraints { make in
            make.top.equalTo(premiumPromptView.snp.bottom).offset(6)
            make.left.right.equalToSuperview().inset(8)
            make.bottom.equalToSuperview().inset(8)
            make.height.equalTo(56)
        }

        backButton.snp.makeConstraints { make in
            make.left.equalToSuperview().inset(24)
            make.width.height.equalTo(44)
            make.top.equalToSuperview().offset(6)
        }

        guideListButton.snp.makeConstraints { make in
            make.right.equalToSuperview().inset(24)
            make.width.height.equalTo(44)
            make.centerY.equalTo(backButton)
        }

        titleLabel.snp.makeConstraints { make in
            make.top.equalToSuperview().offset(6)
            make.left.greaterThanOrEqualTo(backButton.snp.right).offset(12)
            make.right.lessThanOrEqualTo(guideListButton.snp.left).offset(-12)
            make.centerX.equalToSuperview()
        }

        subtitleLabel.snp.makeConstraints { make in
            make.top.equalTo(titleLabel.snp.bottom).offset(2)
            make.leading.trailing.equalToSuperview().inset(72)
        }
    }

    @objc private func didTapTag(_ sender: UIButton) {
        if let text = sender.titleLabel?.text {
            presenter?.userDidSendMessage(text)
        }
    }

    // MARK: - ChatViewable
    func displayMessages(_ messages: [ChatMessage]) {
        self.messages = messages
        tableView.reloadData()
        scrollToBottom()
        updateChatCountLabel()
    }

    func appendMessage(_ message: ChatMessage) {
        messages.append(message)
        isLoading = message.sender == .user
        tableView.reloadData()

        scrollToBottom()
        updateChatCountLabel()
    }

    func showNav() {
        backButton.isHidden = false
    }

    func toogleLoading(_ loading: Bool) {
        isLoading = loading
    }

    func updateCharacterSelection(_ character: CharacterType?) {
        if let character = character {
            selectedCharacter = character
        }

        if let character = selectedCharacter {
            selectedGuide = Character(type: character)
            guideListButton.isHidden = false
            titleLabel.text = character.displayName
            subtitleLabel.text = selectedGuide.bestForLabel
        }
    }


    private func scrollToBottom() {
        guard messages.count > 0 else { return }
        if isLoading {
            let indexPath = IndexPath(row: 0, section: 1)
            tableView.scrollToRow(at: indexPath, at: .bottom, animated: true)

        } else {
            let indexPath = IndexPath(row: messages.count - 1, section: 0)
            tableView.scrollToRow(at: indexPath, at: .bottom, animated: true)
        }
    }


    @objc func tappedBackButton(_ sender: UIButton) {
        dismiss(animated: true)
    }

    @objc func tappedCharacterButton(_ sender: UIButton) {
        let characterSelectionVC = CharacterSelectionViewController()
        characterSelectionVC.delegate = self
        characterSelectionVC.modalPresentationStyle = .fullScreen
        present(characterSelectionVC, animated: true)
    }

    @objc private func dismissKeyboard() {
        view.endEditing(true)
    }

    @objc private func tappedStoreButton(_ sender: UIButton) {
        DSRouter.showDS(from: self) { [weak self] in
            // Update UI after store interaction
            self?.updatePremiumPromptVisibility()
        }
    }

    private func updatePremiumPromptVisibility() {
        let isPremium = StoreKitManager.shared.isPremium
        premiumPromptView.isHidden = isPremium
        dockContainerView.layer.opacity = isPremium ? 0.0 : 1.0
        updateConversationLayout(isPremium: isPremium)

        if !isPremium {
            updateChatCountLabel()
        }
    }

    private func updateChatCountLabel() {
        let currentChatCount = ConditionServices.shared.chatCount
        let totalChat = ConditionServices.shared.totalChatFree
        let remainingCount = max(0, totalChat - currentChatCount)

        chatCountLabel.text = "\(remainingCount) chats remaining"
    }

    private func updateConversationLayout(isPremium: Bool) {
        premiumPromptView.alpha = isPremium ? 0 : 1
        tableTopConstraint?.update(offset: messages.count <= 1 ? 12 : 6)
    }

    // MARK: - Keyboard Handling
    private func setupKeyboardObservers() {
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(keyboardWillShow(_:)),
            name: UIResponder.keyboardWillShowNotification,
            object: nil
        )

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(keyboardWillHide(_:)),
            name: UIResponder.keyboardWillHideNotification,
            object: nil
        )
    }

    private func removeKeyboardObservers() {
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillHideNotification, object: nil)
    }

    @objc private func keyboardWillShow(_ notification: Notification) {
        guard let keyboardFrame = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect,
              let animationDuration = notification.userInfo?[UIResponder.keyboardAnimationDurationUserInfoKey] as? Double else {
            return
        }

        let keyboardHeight = keyboardFrame.height
        let safeAreaBottom = view.safeAreaInsets.bottom

        UIView.animate(withDuration: animationDuration) {
            self.dockContainerView.snp.updateConstraints { make in
                make.bottom.equalTo(self.view.safeAreaLayoutGuide.snp.bottom).offset(-keyboardHeight + safeAreaBottom - 8)
            }
            self.view.layoutIfNeeded()
        }

        // Scroll to bottom to show the latest message
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            self.scrollToBottom()
        }
    }

    @objc private func keyboardWillHide(_ notification: Notification) {
        guard let animationDuration = notification.userInfo?[UIResponder.keyboardAnimationDurationUserInfoKey] as? Double else {
            return
        }

        UIView.animate(withDuration: animationDuration) {
            self.dockContainerView.snp.updateConstraints { make in
                make.bottom.equalTo(self.view.safeAreaLayoutGuide.snp.bottom).offset(-8)
            }
            self.view.layoutIfNeeded()
        }
    }
}

extension ChatViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if section == 0 {
            return messages.count
        } else if section == 1 {
            return isLoading ? 1 : 0
        }

        return 0
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.section == 0 {
            let msg = messages[indexPath.row]
            if msg.sender == .bot {
                guard let cell = tableView.dequeueReusableCell(withIdentifier: "BuddaChatMessageCell", for: indexPath) as? BuddaChatMessageCell else {
                    return UITableViewCell()
                }
                cell.configure(message: msg, character: selectedCharacter)
                return cell
            } else {
                guard let cell = tableView.dequeueReusableCell(withIdentifier: "ChatMessageCell", for: indexPath) as? ChatMessageCell else {
                    return UITableViewCell()
                }
                cell.configure(message: msg, isFromUser: msg.sender == .user)
                return cell
            }
        } else if indexPath.section == 1 {
            guard let cell = tableView.dequeueReusableCell(withIdentifier: "ChatLoadingTVC", for: indexPath) as? ChatLoadingTVC else {
                return UITableViewCell()
            }
            cell.configure(message: "Loading....", isFromUser: false)
            return cell
        } else {
            return UITableViewCell()
        }
    }

}

extension ChatViewController: CharacterSelectionDelegate {
    func didSelectCharacter(_ character: CharacterType) {
        presenter?.restartConversation(with: character)

        presentedViewController?.dismiss(animated: true)
    }
}
